### ISSUE TITLE
RPI. Image Default root password

### ISSUE THREAD

**Issue by guzongzi** [AlmaLinux/raspberry-pi#16]
What's the default root password for almaliunx 9.0?
Can't login via ssh.
Or maybe ssh root user login is not enabled?
Useing AlmaLinux-9-RaspberryPi-9.0-20220615.aarch64 headless.

**Comment by srbala** [comment]
SSH is deprecated in upstream, https://www.redhat.com/en/blog/openssh-scp-deprecation-rhel-9-what-you-need-know

https://github.com/AlmaLinux/raspberry-pi/blob/master/AlmaLinux-9-RaspberryPi-console.aarch64.ks#L9

**Comment by srbala** [comment]
@guzongzi since it is a more informational type, I'm closing this issue and pinning it for others' reference.

**Comment by thomasnaudin** [comment]
Does it mean that there is no way one could login via ssh with a fresh flashed sd-card ?
Should I use a keyboard & a screen to configure my Raspberry ?

**Comment by e3b0c442** [comment]
Came upon this while doing research. @srbala I think there may be a misunderstanding -- SSH as a whole was absolutely not deprecated with RHEL9, just the SCP file copy protocol.

Surely something else must be at play here.

**Comment by codyro** [comment]
I believe @srbala misspoke regarding SSH, it's definitely just SCP. I'll try to test this out shortly however without looking I'm guessing the shipped `/etc/ssh/sshd_config` has `PermitRootLogin` set to `without-password` or something along those lines. `sshd` is being started based off the kickstart file. Are you just getting login error or is SSH not responding at all?

**Comment by metalefty** [comment]
Will be addressed with updated 9.2 image, hang tight.

**Comment by feluxe** [comment]
It still doesn't work.

**Comment by metalefty** [comment]
Raise your own issue for your issue.
