### ISSUE TITLE
Using AL9.0 image with 3b+

### ISSUE THREAD

**Issue by GrigoryPrutskov** [AlmaLinux/raspberry-pi#17]
Hi

I'm trying to run AL9 on rpi 3b+ using [these images](https://repo.almalinux.org/rpi/9/images/). On the first run boot stucks at "a start job is running for security auditing service". After hard reset all next boots stuck on "(1 of 2) a start job is running for user login management/ (2 of 2) a start job is running for d-bus system message bus". The issue is reproduced on different boards/power supplies/sd cards. May be I waste my time cause AL9 just doesn't support rpi < 4?

Thanks

**Comment by srbala** [comment]
@GrigoryPrutskov are both text and graphical images that cause this issue for you. I do not own a 3b+ pi device to validate images.

https://github.com/AlmaLinux/raspberry-pi/blob/master/AlmaLinux-9-RaspberryPi-console.aarch64.ks#L53-L71

You may need some adjustments on your SD card written from the above steps.

**Comment by GrigoryPrutskov** [comment]
@srbala
I described behavior of cli image. Another one turns off a display during boot, so I'm not sure about it.

I checked cmdline.txt from the image and it already has parameters with values from you example. Additionally, I extended root partition size before boot manually with fdisk and resize2fs, but the issue still exist.

Also I've tried to create my own image file using "build_al9_console" script from this git repo on the clean AL9 aarch system running via qemu (with EPEL for aplliance-progs). At the very end of the installation I've got following error:
```

Backup stored at /var/lib/authselect/backups/2022-10-25-17-42-27.b4iIX3
Profile "sssd" was selected.
The following nsswitch maps are overwritten by the profile:
- passwd
- group
- netgroup
- automount
- services

Make sure that SSSD service is configured and enabled. See SSSD documentation for more information.

Adding port '22/tcp' to default zone.
success
Writing kickstart file.
Writing GRUB Legacy config.
 

Traceback (most recent call last):
  File "/bin/appliance-creator", line 193, in <module>
    sys.exit(main())
  File "/bin/appliance-creator", line 155, in main
    creator.configure()
  File "/usr/lib/python3.9/site-packages/imgcreate/creator.py", line 799, in configure
    self._create_bootconfig()
  File "/usr/lib/python3.9/site-packages/appcreate/appliance.py", line 619, in _create_bootconfig
    self._create_grub_config()
  File "/usr/lib/python3.9/site-packages/appcreate/appliance.py", line 337, in _create_grub_config
    options = self._kernel_cmdline_append()
  File "/usr/lib/python3.9/site-packages/appcreate/appliance.py", line 268, in _kernel_cmdline_append
    for s in self.ks.handler.btrfs.btrfsList:
AttributeError: 'RHEL9_BTRFS' object has no attribute 'btrfsList'
Unmounting directory /var/tmp/imgcreate-tyyf6nmn/install_root/boot
Unmounting directory /var/tmp/imgcreate-tyyf6nmn/install_root/
Removing compat symlinks
Unmapping /dev/loop0
Losetup remove /dev/loop0
```

**Comment by GrigoryPrutskov** [comment]
upd:
RockyLinux 9 for rpi demonstrates same problem. But at the same time Oracle Linux 9 with UEK kernel works fine. So I'm leaning towards that is RHEL9 issue (at least it kernel) not AlmaLinux.

**Comment by GrigoryPrutskov** [comment]
Adding brcmfmac module to blacklist solved the problem. (On RockyLinux too). Please close this issue.

**Comment by jaboutboul** [comment]
Hmm, maybe we should build a separate image for the 3 models with this blacklisted?

**Comment by GrigoryPrutskov** [comment]
Or at least add this to readme

**Comment by metalefty** [comment]
Hi, I wrote up how to modify RasPi images RasPi 3 capable. I would be happy if it helps someone encountered the same issue.

## 1. Download Image
```
wget https://repo.almalinux.org/rpi/9/images/AlmaLinux-9-RaspberryPi-latest.aarch64.raw.xz
xz -d AlmaLinux-9-RaspberryPi-latest.aarch64.raw.xz
```

## 2. Mount Image to Modify
```
LODEV=$(losetup -f)
sudo partx -a AlmaLinux-9-RaspberryPi-latest.aarch64.raw
```
```
sudo fdisk -lu ${LODEV}
Disk /dev/loop0: 2.75 GiB, 2936012800 bytes, 5734400 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x5ea2038d

Device       Boot  Start     End Sectors  Size Id Type
/dev/loop0p1 *      8192  593919  585728  286M  c W95 FAT32 (LBA)
/dev/loop0p2      593920  788479  194560   95M 82 Linux swap / Solaris
/dev/loop0p3      788480 5476351 4687872  2.2G 83 Linux                        <----- This is the mount target
```
```
sudo mount ${LODEV}p3 /mnt
```

## 3. Add brcmfmac to blacklist

```
sudo bash -c "echo 'blacklist bcrmfmac' > /mnt/etc/modprobe.d/raspi-blacklist.conf"
```


## 4. Unmount and cleanup 

```
sudo umount /mnt
sudo losetup -d ${LODEV}
```

Finally, write the modified `AlmaLinux-9-RaspberryPi-latest.aarch64.raw` to SD card any way you like.

**Comment by metalefty** [comment]
This script would also help modifying the image Pi 3 capable.
https://gist.github.com/metalefty/3a52837be28da46f2abd268f23ccf75a

**Comment by josueneo** [comment]
Blacklisting brcmfmac will disable WIFI capabilities on the RPI 3B.

**Comment by psgreco** [comment]
if you need to use the module, what you can do is decompress the txt.xz firmware file, that should avoid the crash too

**Comment by metalefty** [comment]
I think the issue is identical to: https://github.com/NixOS/nixpkgs/issues/200326

However, I don't understand why decompressing `brcmfmac43430-sdio.raspberrypi,3-model-b.txt.xz` can avoid the crash.

**Comment by metalefty** [comment]
Here's the boot log.
https://github.com/AlmaLinux/raspberry-pi/assets/941609/8c3074a2-310f-475a-b932-54dfac0fe539

**Comment by metalefty** [comment]
@andrewlukoshko While I'm testing kernel updates you asked me, I found that updating kernel to 6.1.31 solved this issue.

https://build.almalinux.org/build/6846
https://build.almalinux.org/build/6847

**Comment by metalefty** [comment]
This was my mistake in testing, the issue is not solved.

**Comment by metalefty** [comment]
The issue is resolved now on RPi 3B+

**Comment by owainkenwayucl** [comment]
Just a note to say I also just had this problem with the most up to date 9.4 image aka https://repo.almalinux.org/almalinux/9/raspberrypi/images/AlmaLinux-9-RaspberryPi-9.4-20240801.aarch64.raw.xz

**Comment by owainkenwayucl** [comment]
Also note for people who get here - linux firmware updates via `dnf` will replace the file but since the decompressed old one is still there the system appears to be fine. You might want to update the decompressed on manually.

**Comment by metalefty** [comment]
I already know that. What I want to know now is why decompressing the file resolves the issue.

**Comment by ncbright** [comment]
+1 on this still being an issue on Raspberry Pi 3B+.  Looks to be the same kernel oops as in the video posted above.

This is with AlmaLinux-9-RaspberryPi-9.4-20240801.aarch64.raw.xz.  It is not an issue on a Raspberry Pi 5.

Using a Pi5 and starting with the 20240801 image, a 'yum update' to get to raspberrypi2-kernel4-6.6.51-20241008.v8.1.el9.aarch64 and linux-firmware-20240905-146.el9.noarch.

Took that SD card and booted on the Pi 3B+ to replicate the problem.

Adding brcmfmac module to blacklist allows the 3B+ to boot.  as expected, nmcli dev wifi list shows no wifi adapters.

doing a modprobe brcmfmac does load the module, but results in the oops below.

`[root@almalinux ~]# lsmod | grep brc
brcmfmac              352256  1
brcmutil               24576  1 brcmfmac
cfg80211              987136  1 brcmfmac
`

`[  224.754938] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[  224.779511] Loaded X.509 cert 'benh@debian.org: 577e021cb980e0e820821ba7b54b4961b8b4fadf'
[  224.780587] Loaded X.509 cert 'romain.perier@gmail.com: 3abbc6ec146e09d1b6016ab9d6cf71dd233f0328'
[  224.781607] Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[  224.782597] Loaded X.509 cert 'wens: 61c038651aabdcf94bd0ac7ff06c7248db18c600'
[  224.861020] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[  224.867224] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[  224.867885] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.raspberrypi,3-model-b.bin failed with error -2
[  224.869690] usbcore: registered new interface driver brcmfmac
[  224.969183] Unable to handle kernel write to read-only memory at virtual address ffffffc0807a717b
[  224.969301] Mem abort info:
[  224.969332]   ESR = 0x000000009600004f
[  224.969370]   EC = 0x25: DABT (current EL), IL = 32 bits
[  224.969421]   SET = 0, FnV = 0
[  224.969453]   EA = 0, S1PTW = 0
[  224.969486]   FSC = 0x0f: level 3 permission fault
[  224.969531] Data abort info:
[  224.969560]   ISV = 0, ISS = 0x0000004f, ISS2 = 0x00000000
[  224.969611]   CM = 0, WnR = 1, TnD = 0, TagAccess = 0
[  224.969661]   GCS = 0, Overlay = 0, DirtyBit = 0, Xs = 0
[  224.969712] swapper pgtable: 4k pages, 39-bit VAs, pgdp=000000000131f000
[  224.969773] [ffffffc0807a717b] pgd=1000000001d6e003, p4d=1000000001d6e003, pud=1000000001d6e003, pmd=10000000026a8003, pte=006000000aa37f83
[  224.969893] Internal error: Oops: 000000009600004f [#1] PREEMPT SMP
[  224.969952] Modules linked in: brcmfmac brcmutil cfg80211 nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip_set nf_tables nfnetlink cmac algif_hash aes_arm64 aes_generic algif_skcipher af_alg bnep hci_uart btbcm bcm2835_codec(C) bluetooth raspberrypi_hwmon v4l2_mem2mem snd_bcm2835(C) bcm2835_v4l2(C) bcm2835_isp(C) snd_pcm videobuf2_dma_contig bcm2835_mmal_vchiq(C) videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 ecdh_generic ecc videodev rfkill libaes snd_timer videobuf2_common snd mc raspberrypi_gpiomem vc_sm_cma(C) joydev uio_pdrv_genirq uio sch_fq_codel drm fuse drm_panel_orientation_quirks backlight ipv6 crc_ccitt
[  224.970646] CPU: 3 PID: 54 Comm: kworker/3:1 Tainted: G         C         6.6.51-20241008.v8.1.el9 #1
[  224.970729] Hardware name: Raspberry Pi 3 Model B Rev 1.2 (DT)
[  224.970783] Workqueue: events request_firmware_work_func
[  224.970846] pstate: 20000005 (nzCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[  224.970911] pc : brcmf_fw_complete_request+0x49c/0x9f0 [brcmfmac]
[  224.971035] lr : brcmf_fw_complete_request+0x148/0x9f0 [brcmfmac]
[  224.971140] sp : ffffffc0805ebc20
[  224.971174] x29: ffffffc0805ebcd0 x28: ffffff80061c8680 x27: ffffffede2df6000
[  224.971245] x26: 000000000000036a x25: ffffff800a584900 x24: ffffffc0805ebc68
[  224.971316] x23: ffffffc0807a7000 x22: ffffff80061c8680 x21: ffffffed6a8cb248
[  224.971387] x20: ffffff80061c83c0 x19: ffffff800a584920 x18: 0000068845ca8410
[  224.971459] x17: 00000113388ecd68 x16: ffffffede24af838 x15: 636272777078740a
[  224.971531] x14: 31313d7665726d6f x13: 6c770a3465343178 x12: 0000000000000000
[  224.971602] x11: 00000000fffffffd x10: dead000000000100 x9 : ffffffed6a8b9000
[  224.971673] x8 : 0101010101010101 x7 : 7f7f7f7f7f7f7f7f x6 : 6c656c6271613500
[  224.971744] x5 : 000000000000003d x4 : 0000000000000030 x3 : ffffffc0807a717b
[  224.971814] x2 : 0000000000000023 x1 : 0000000000000041 x0 : ffffffede25e0c00
[  224.974032] Call trace:
[  224.976240]  brcmf_fw_complete_request+0x49c/0x9f0 [brcmfmac]
[  224.978532]  brcmf_fw_request_done+0xdc/0x1a0 [brcmfmac]
[  224.980812]  request_firmware_work_func+0x58/0xb0
[  224.983016]  process_one_work+0x148/0x388
[  224.985179]  worker_thread+0x338/0x450
[  224.987314]  kthread+0x120/0x130
[  224.989414]  ret_from_fork+0x10/0x20
[  224.991513] Code: f9400799 17ffff24 39401861 52800462 (39000062)
[  224.993609] ---[ end trace 0000000000000000 ]---
`

**Comment by ncbright** [comment]
This line might give a clue as to why uncompressing the firmware file lets booting proceed.

`Direct firmware load for brcm/brcmfmac43430-sdio.raspberrypi,3-model-b.bin failed with error -2  `
