### ISSUE TITLE
fix for wlan (cm4)

### ISSUE THREAD

**Issue by virgilhuxley** [AlmaLinux/raspberry-pi#18]
2022-10-30  
I just installed the latest almalinux on my raspberry pi cm4 using:  
89773106f23407efb5258d7185d2005c6ed4f98f2ad23916948be573eb2efb95  AlmaLinux-8-RaspberryPi-latest.aarch64.raw.xz

Everything was seamless except for wifi.

There was no wifi driver file for a pi CM4 in `/lib/firmware/brcm`

I found a post by @geerlingguy in [openwrt forums](https://forum.openwrt.org/t/raspberry-pi-cm4-wifi-not-working/90280/4) with the solution.

```sh
# cp /lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,4-model-b.txt /lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,4-compute-module.txt
```

running the above command and rebooting resolved my issue.

It would seem that openwrt has implemented something [similar](https://github.com/openwrt/openwrt/commit/b1db5585557ed069027767a80c31c6f1f2920196) into their upstream

**Comment by metalefty** [comment]
This should be resolved now.
https://git.almalinux.org/rpms/linux-firmware-raspberrypi/commit/f686057b99ace67e9fe82ff8fd1aa182abdc7ebb

**Comment by metalefty** [comment]
Feel free to come back if it doesn't work on CM4.
