### ISSUE TITLE
resizing part

### ISSUE THREAD

**Issue by HVRyan** [AlmaLinux/raspberry-pi#2]
as provided instructions didn't do it

> [root@AlmaPi ~]# resizepart 3
> resizepart: not enough arguments
> Try 'resizepart --help' for more information.

Went with another route, taken from getting CentOS 8 installed:

`growpart /dev/<device>`

then was able to do `resize2fs /dev/mmcblk0p3`

I'd post the buffer here but did it via console, not SSH.

**Comment by jaboutboul** [comment]
This has been fixed in the updated image via merging of @arrfab's rootfs-expand:

https://github.com/CentOS/sig-core-AltArch/blob/2eaa9c3ab33a7df96d0ac127c9667341c4b909db/centos-release/SPECS/centos-release.spec#L241
