### ISSUE TITLE
AlmaLinux 9 is not booting

### ISSUE THREAD

**Issue by srunow** [AlmaLinux/raspberry-pi#20]
I've tried two images on a Raspberry Pi Model 3B+ without gnome from https://repo.almalinux.org/rpi/9/images/ (files timestamp 17-Nov-2022 00:50) but they're not working. To be specific, the RasPi is booting but is trying endless (of course not literally) to start some services. I didn't noted every service but D-Bus Management System is one of them and firewalld as well, whereby firewalld is aborted after about two minutes with status failed.

**Comment by GrigoryPrutskov** [comment]
https://github.com/AlmaLinux/raspberry-pi/issues/17
Try to blacklist brcmfmac kernel module

**Comment by metalefty** [comment]
Try this: https://github.com/AlmaLinux/raspberry-pi/issues/17#issuecomment-1500153217

**Comment by metalefty** [comment]
duplicate of #17
