### ISSUE TITLE
'v3d' Driver on 9.2!

### ISSUE THREAD

**Issue by sallyhaj** [AlmaLinux/raspberry-pi#32]
Hello there, I have tried "https://repo.almalinux.org/rpi/9/images/AlmaLinux-9-RaspberryPi-GNOME-latest.aarch64.raw.xz" on Raspberry Pi 4, first thing, I have updated to 9.2, then I have checked the GUI, it's very sluggish, I've checked the driver and it's showing that "llvmpipe", which seems the system couldn't recognize the other one, by the way in "config.txt" this line "dtoverlay=vc4-fkms-v3d" is there.
What am I missing to get the system GPU hardware acceleration supported?

Thank you.
![9gWkAoxLQcu4tuy0qaXGJw](https://github.com/AlmaLinux/raspberry-pi/assets/109706/e3450cc2-bb5e-4c1a-81ae-e04a69d69329)
![TtEoiobKRHG4ATBEvkDc0Q](https://github.com/AlmaLinux/raspberry-pi/assets/109706/868a9770-f094-4233-9bdd-6b3c4a2693b3)

**Comment by metalefty** [comment]
I would like to fix this but not sure what I should do.

**Comment by pastalian** [comment]
It seems that vc4 and v3d are disabled in mesa. Could this be the cause? I don't have the hardware to test though.
https://git.almalinux.org/rpms/mesa/src/branch/c9/SPECS/mesa.spec#L26-L27

**Comment by sallyhaj** [comment]
Thank you @pastalian for pointing that out.
In the logs of https://git.almalinux.org/rpms/mesa/src/branch/c9/SPECS/mesa.spec:
```
* Fri Mar 26 2021 Adam Jackson <ajax@redhat.com> - 21.0.1-3
- Split out with_r300 and with_r600
- Disable r300, r600, etnaviv, lima, vc4 and v3d in RHEL

```
Which was enabled before, but from 21.0.1-3 release it disabled.
Maybe we can get Fedora Mesa as an example:
https://src.fedoraproject.org/rpms/mesa/blob/rawhide/f/mesa.spec
I can test on RPi4-5
Thank you.

**Comment by metalefty** [comment]
Indeed.

```
$ rpm -ql mesa-dri-drivers | egrep "v3d|vc4"
$ 
```

**Comment by metalefty** [comment]
It worked now.

![WIN_20240624_10_30_49_Pro](https://github.com/AlmaLinux/raspberry-pi/assets/941609/39eb2926-7592-4184-b81a-7f16226fe33e)

**Comment by metalefty** [comment]
Try this if you would like to try it locally: https://build.almalinux.org/build/14861

**Comment by sallyhaj** [comment]
Thank you @metalefty 
I want to test it on RPi5, should I just download the packages and install them manually? or if there is something similar to Fedora "sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2022-fff66108a5" in Almalinux?
Thank you.

**Comment by metalefty** [comment]
The packages are now released officially. Just do `dnf update` then you will grab the driver.

**Comment by metalefty** [comment]
New images that include V3D drivers are released.

**Comment by sallyhaj** [comment]
I've just updated, it's really really fast.
Thank you so much @pastalian for discovering the issue.
Thank you @metalefty For your all your work.
![desDpsA](https://github.com/AlmaLinux/raspberry-pi/assets/109706/dcc17802-9c3a-4d27-8801-c39120e31a8e)
![lufzclZ](https://github.com/AlmaLinux/raspberry-pi/assets/109706/57ade39b-54b0-4aed-9ffa-6f4c0cac558a)

**Comment by metalefty** [comment]
My pleasure. Thank you for the patience!
