### ISSUE TITLE
raspberrypi2-kernel4-devel should be marked installonly

### ISSUE THREAD

**Issue by lightdot** [AlmaLinux/raspberry-pi#39]
Basically, as the title says. A manual solution is to add a `installonlypkgs=raspberrypi2-kernel4-devel` line to `/etc/dnf/dnf.conf`.

Without this, only a single `raspberrypi2-kernel4-devel` is kept as the newer kernel installs. Not having a corresponding `raspberrypi2-kernel4-devel` package for older `raspberrypi2-kernel4` kernels causes issues e.g. when building custom kernel modules.

**Comment by metalefty** [comment]
It will be resolved soon: https://git.almalinux.org/rpms/raspberrypi2/pulls/2
