### ISSUE TITLE
Raspberry Pi 5

### ISSUE THREAD

**Issue by dpst999** [AlmaLinux/raspberry-pi#40]
Unable to run alamlinux on raspberry pi 5. It is not booting at all

**Comment by metalefty** [comment]
There's no images available for Raspberry Pi 5 now. Work in progress. Hold on.

**Comment by pellucida** [comment]
I couldn't find a RPi 5 AL8 image several weeks ago  (March 2024) and tried using the Raspberry Pi OS kernel  and modules to replace the AL8 equivalents on the RPi 4 AL8 image. Boots ok, and updates fine. The kernel is 6.6.x not the AL8 aarch64 native 6.1 but doesn't seem to matter. Haven't tried with Gnome  yet as I have been busy.
I think I got all the details in
https://github.com/pellucida/almalinux8-on-raspberry-pi5
but have to return to it soon to automate the process.
Hopefully official images will appear and no such skulduggery will then be required.

**Comment by metalefty** [comment]
Thanks!

Anyway, what we should do is to update [raspberrypi2](https://git.almalinux.org/rpms/raspberrypi2/src/branch/c9) package that contains files for Pi 5 such as `*.dtb` and bootcode.

**Comment by metalefty** [comment]
I could boot RPi 5 successfully. There are still several things to do though. There's no scheduled release right now but surely approaching!

![WIN_20240527_16_28_39_Pro](https://github.com/AlmaLinux/raspberry-pi/assets/941609/0b6413bc-2cc6-4a16-9e82-52d29c5855a8)

**Comment by pellucida** [comment]
Thanks *metalefty*, 
I notice that this for AL9.4. 
Is AL8 being worked on?
Or is the plan to get 9.4 (kernel 6.6) working and back porting the fixes to AL8 (kernel 6.1)?

**Comment by andrewlukoshko** [comment]
RPi5 is supported in AlmaLinux 8 images as well

**Comment by pellucida** [comment]
Many thanks Andrew.
Al8.10 works a treat on a 8G RPi5.
I am probably a bit dense but its not obvious to me where the AL8 RPi specific kernel sources are kept.
The kernel version for AL8 etc on x86_64 is 4.18.0 but on RPi its 6.6.28 so must be different source trees.
I wish to build the ZFS kmods but I am not sure whether I can do this on the RPi (slow) or whether all the kernel stuff is done in a cross development environment (PITA to set up.)
Thanks again.

**Comment by andrewlukoshko** [comment]
@pellucida RPi kernel source for AL8 is here:
https://git.almalinux.org/rpms/raspberrypi2/src/branch/a8
Or you can download src.rpm here:
https://vault.almalinux.org/8/raspberrypi/Source/Packages/raspberrypi2-6.6.28-20240423.v8.1.el8.src.rpm

**Comment by metalefty** [comment]
Closing. Raise a new issue if you still have an issue.
