### ISSUE TITLE
Jenkins pipeline for building RPi images

### ISSUE THREAD

**Issue by andrewlukoshko** [AlmaLinux/raspberry-pi#41]
Currently we're building images manually.
But we need to implement Jenkins pipeline to do this automatically.

Requirements:
- Correct file naming. Examples:
```
AlmaLinux-8-RaspberryPi-8.9-20231127.aarch64.raw.xz
AlmaLinux-8-RaspberryPi-GNOME-8.9-20231127.aarch64.raw.xz
AlmaLinux-9-RaspberryPi-9.3-20231127.aarch64.raw.xz
AlmaLinux-9-RaspberryPi-GNOME-9.3-20231127.aarch64.raw.xz
```
- Upload images to Amazon S3
- Announce in SIG/AltArch Mattermost channel just like we do for Live Media.

**Comment by AlexBaranowski** [comment]
@andrewlukoshko maybe instead of using Jenkins, github actions would be better. You could then create a release that will not be dependent on AWS S3 and won't generate costs. The build logs are also nice addition ;)

**Comment by AlexBaranowski** [comment]
Edit: https://github.com/actions/runner-images/issues/2536,

I do not mind build in container that would have appliance-builder hacked, but ATM the GH Actions do not have Linux aarch64/arm64 builder. So... NVM. Custom runner for just RPI when You have proper Jenkins with hosts that are able to build it natively is useless ATM.

**Comment by codyro** [comment]
> Edit: https://github.com/actions/runner-images/issues/2536,
> 
> 
> 
> I do not mind build in container that would have appliance-builder hacked, but ATM the GH Actions do not have Linux aarch64/arm64 builder. So... NVM. Custom runner for just RPI when You have proper Jenkins with hosts that are able to build it natively is useless ATM.

https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/ 😀

**Comment by AlexBaranowski** [comment]
@codyro Yeah, but I'm not sure if it's suitable. I would like to do that, but this need organization billing enabled and paid plan.

From post that you linked:

```
These runners are available to our customers on our GitHub Team and Enterprise Cloud plans. We expect to begin offering Arm runners for open source projects by the end of the year. Customers can begin using these runners today by creating an Arm runner in their organization/enterprise, and then updating the runs-on syntax in their GitHub Actions workflow file to call that runner name. Find out more information on how to set up Arm-hosted runners in [this video](https://www.youtube.com/watch?v=cgI6SBP8pEM) or in our [public documentation](https://docs.github.com/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners). To learn more about runner-per-minute pricing, check out the [documentation](https://docs.github.com/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates).
```

**Comment by andrewlukoshko** [comment]
@AlexBaranowski yes we're considering switching to GitHub Actions for this using self-hosted runner in AWS.

**Comment by AlexBaranowski** [comment]
@andrewlukoshko if you give me 2-3 days I could test it in my free time. I would use different host provider (hetzner -> dirty cheap). Then I could provide whole solution except host and out-of-scope for GH action configuration.
