### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by LagunaPower** [AlmaLinux/raspberry-pi#59]
hello,
I’m trying to build an image of Almalinux8 for rapsberry pi 4 but when using build_al8_console (from the github), I have a lot of errors and it doesn’t work... for information I didn’t change the kickstart file.

here the log file: [log_file.txt](https://github.com/user-attachments/files/16398672/log_file.txt)

**Comment by codyro** [comment]
Hello,

@andrewlukoshko saw an issue when you posted this in chat earlier this morning. You'll want to use aarch64 for RPi. 

> User-Agent: constructed: 'libdnf (AlmaLinux 8.10; generic; Linux.x86_64)'

**Comment by metalefty** [comment]
Not an issue and this is multiposted in 3 channels! :( (#general #SIG/AltArch and here)  Closing.
